name: village_noel
description: Une application mobile pour le marché de Noël à Landerneau.
version: 1.0.0+8

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  flutter_svg: ^1.0.3
  url_launcher: ^6.2.5
  webview_flutter: ^4.4.2
  font_awesome_flutter: ^10.6.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  # Ajouts pour le menu interactif et animations
  # particles_flutter: ^2.0.0  # Optionnel : pour les particules de neige
  # rive: ^0.12.3              # Optionnel : pour les animations vectorielles

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0

flutter:
  fonts:
    - family: GillSansBold
      fonts:
        - asset: fonts/GillSansBold.otf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/maps/
    - assets/icons/
    - assets/gifs/
    - assets/game/
    # Ajoutez ce chemin si vous utilisez Rive
    # - assets/animations/
